### ISSUE TITLE
Creating a new Project works but diverweb doesn't think so

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/diverweb-issues#92]
[2023-02-08 13:04:40,639] DEBUG in diverRPC: Args: None | Body: {'description': 'Demostration of DIVER for UDP', 'name': 'UDP_demo'}
[2023-02-08 13:04:40,715] DEBUG in diverRPC: proc API_CreateProject called, args ('testuser', 'UDP_demo', 'Demostration of DIVER for UDP'), result (first 1000 chars only): [{'new_project_id': 10}]
127.0.0.1 - - [08/Feb/2023 13:04:40] "POST /api/v0/project/new HTTP/1.1" 200 -
[2023-02-08 13:04:40,767] DEBUG in diverRPC: ----------------------------------------------------
[2023-02-08 13:04:40,768] DEBUG in diverRPC: Args: ImmutableMultiDict([('projectid', 'undefined')]) | Body: None
127.0.0.1 - - [08/Feb/2023 13:04:40] "GET /api/v0/project/info?projectid=undefined HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/whv001/mambaforge/lib/python3.9/site-packages/flask/app.py", line 2091, in _call_
...50 messages...
  File "/Users/whv001/mambaforge/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1366, "Incorrect integer value: 'undefined' for column ``.``.`inProjectId` at row 1")

The new project (10) was created. It just didn't communicate that back to diverweb apparently.

**Comment by WValenti** [comment]
Both diverweb and diverRPC are pulled to be sure they're current, and I got this error again...
![Screen Shot 2023-03-02 at 10 42 21 AM](https://user-images.githubusercontent.com/3909236/222477111-a1ad7d4d-4c15-4f89-a4fa-fe0e2098ceff.png)

**Comment by Viqsi** [comment]
That is a completely unrelated bug. Please create new issues for situations like this going forward.
